### ISSUE TITLE
model uploader failing

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/archive.bioimage.io#415]
Hi there, 

I'm trying to upload a model with format and the system keeps failing in different ways:

1. I've tried uploading a model several times and now whenever I want to access the folder where I've been accessing during the last 24h, I cannot. Howver, I can access any other folder in my computer. Is it saving in memory any sort of path?

  ![Screenshot 2024-07-16 at 10 39 21](https://github.com/user-attachments/assets/6f1b0f2d-ab21-4eeb-8ddd-7cfc3f9d9848)

2. When I load my model (version 0.4.10 passing all the tests with bioimageio.core 0.5.11), the system allows me indicating an uploader name but not an email. However, then it complains about the email of the uploader. 
  ![Screenshot 2024-07-15 at 17 54 05](https://github.com/user-attachments/assets/d714a601-e716-4f0a-8e4c-d1bf53b4bad5)
 not an email. However, then it complains about the email of the uploader. 
  
  ![Screenshot 2024-07-15 at 17 54 15](https://github.com/user-attachments/assets/983aa48e-22a9-4776-9a81-1c863551734e)

3. I try it again without indicating any name for the uploader, it passes the validation but does not generate a nickname and the button "regenarete a nickname" does not work, so I cannot upload the model. 
![Screenshot 2024-07-15 at 18 13 32](https://github.com/user-attachments/assets/baa344b5-fd8e-4113-b938-bfea45d89a11)

4. The previous steps, when uploading the model as a zip file, do not work and the validation does not pass. However, when I upload the files individually, it seems to "work"

@oeway @FynnBe @ctrueden @nilsmechtel

**Comment by FynnBe** [comment]
[this PR](https://github.com/bioimage-io/collection/pull/85) broke the backend as the resulting json file was invalid.

**Comment by FynnBe** [comment]
I fixed it [here](https://github.com/bioimage-io/collection/commit/de19018ebe4aa59202c714af7a1bfc697efe153c)

**Comment by FynnBe** [comment]
oh, but I think you didn't even get to the backend...

**Comment by FynnBe** [comment]
This issue seems to be with the uploader itself only (sorry for the unrelated spam)

**Comment by esgomezm** [comment]
The backend may be for the validation as it was giving random error messages. Still the uploader does not work

**Comment by oeway** [comment]
@esgomezm The uploader is fixed, this is maybe due to recent update on the backend to the spec version. It should get you successfully to the nickname generation, so you can then click upload.

<img width="1364" alt="Screenshot 2024-07-17 at 00 14 43" src="https://github.com/user-attachments/assets/7a139552-cf7c-4fb8-b186-c2ab547314d1">


I haven't looked into the review feature, need to check with Fynn.

**Comment by esgomezm** [comment]
Hi @oeway still not working. I'm logged in and it's complaining about usernames or emails. I cannot add my email as uploader, by the way. 

![Screenshot 2024-07-17 at 10 58 56](https://github.com/user-attachments/assets/633e8b80-8f48-49b8-9a0b-85273e23a8b0)

**Comment by esgomezm** [comment]
Ok, I managed but it needs loging out and inn. Also, I'm not sure if this is the validator but, once it fails, it's not possible to change something and run it again in a way that it works. I needed to restart the uploading. 
On the other hand, the source error is weird. There is a chance to fill the source URL but then the validation fails. Is it due to the old version of the specs that I'm using in my model?
![Screenshot 2024-07-17 at 11 08 33](https://github.com/user-attachments/assets/3b6259b2-ecad-41ee-a56b-681cfd82b410)

**Comment by oeway** [comment]
> Hi @oeway still not working. I'm logged in and it's complaining about usernames or emails. I cannot add my email as uploader, by the way.

Sorry about that. The idea is that you don't need to type your email, it will be taken automatically from the login credentials.

> Ok, I managed but it needs loging out and inn. Also, I'm not sure if this is the validator but, once it fails, it's not possible to change something and run it again in a way that it works. I needed to restart the uploading. On the other hand, the source error is weird. There is a chance to fill the source URL but then the validation fails. Is it due to the old version of the specs that I'm using in my model? 

I will check that. I think the issue right now is that I cannot reproduce these, would it be possible to do a zoom session together sometime soon so we can fix them on spot?

**Comment by esgomezm** [comment]
Hi Wei, sure! What about next week or when is it better for you?

**Comment by oeway** [comment]
sounds good! I will message you the calendar link.

**Comment by oeway** [comment]
this should have been fixed now, please feel free to reopen if it still happens.
