### ISSUE TITLE
Cannot sign into model upload website

### ISSUE THREAD

**Issue by mattaq31** [bioimage-io/archive.bioimage.io#440]
Hi,

I'm attempting to upload a new model to BioImage.IO.  However, I am unable to take any action as the website ([https://bioimageio-uploader.netlify.app/#/uploader/add](https://bioimageio-uploader.netlify.app/#/uploader/add) is not allowing me to sign-in (screen recording attached).

On further investigation it appears that the login button is at fault as it is not returning a useful URL for signing in.  Would you be able to investigate this issue or advice on alternative methods for uploading a model?

Thanks in advance.

https://github.com/user-attachments/assets/95bc7641-64cc-4d70-93a6-662aa1cd4e86

**Comment by FynnBe** [comment]
I can still reproduce this issue.

**Comment by FynnBe** [comment]
bioimage.io login is back online

**Comment by mattaq31** [comment]
I am still unable to login or upload models - the button still seems unclickable.  Does the update take some time for it to roll out to the website?

Thanks!

**Comment by FynnBe** [comment]
can confirm it's down again. help please @oeway

**Comment by FynnBe** [comment]
It does work again now...

**Comment by mattaq31** [comment]
@FynnBe it's still not working on my end!  Checked on both Mac and Windows.

**Comment by FynnBe** [comment]
@oeway  please advise

**Comment by oeway** [comment]
Hi, sorry, it seems there are some regression issue due to recent upgrade in hypha, now it should be back, please check and let me know if it works.

**Comment by FynnBe** [comment]
works again, please reopen if the login issue reappears

**Comment by mattaq31** [comment]
Still not working... is there some other way for me to upload models to bioimage.io?

**Comment by oeway** [comment]
@mattaq31 I am on it now, I can reproduce the issue.

**Comment by oeway** [comment]
The issue is that the current server crash after running for a while, and I cannot find the exact issue yet.

Rolled back to a previous hypha version, please check if this version works.

Sorry about this.

@mattaq31

**Comment by mattaq31** [comment]
Unfortunately still doesn't seem to be working...

**Comment by oeway** [comment]
I had to go back to a much earlier version it seems, now seems to be working for a while without crashing.

Thanks a lot for your patience.

**Comment by FynnBe** [comment]
I implemented upload via issue request: https://github.com/bioimage-io/collection/issues/new?template=-bioimageiobot--please-upload.md

See https://github.com/bioimage-io/collection/issues/123 and https://github.com/bioimage-io/collection/issues/124 for examples/

The title should include the concept id (e.g. polite-pig; it is not yet generated for you if missing).
Maybe this can be an interim backup solution...

**Comment by mattaq31** [comment]
@oeway unfortunately login still doesn't work... I'm happy to use the issue request uploader instead though, which I'll do later today (thanks @FynnBe)

**Comment by mattaq31** [comment]
@FynnBe just to confirm can I just choose any adjective-noun format for my models?  Is there some way for me to know which ones are already taken?

**Comment by FynnBe** [comment]
> [@FynnBe](https://github.com/FynnBe) just to confirm can I just choose any adjective-noun format for my models?


no, we restrict the choices to fixed lists defined in our collection config: https://github.com/bioimage-io/collection/blob/73cf68a9c0f01df1d0f25089161ea6d6ddd768b5/bioimageio_collection_config.json#L542

> Is there some way for me to know which ones are already taken?

For convenience I setup generation of a file with all available (untaken) description IDs: https://uk1s3.embassy.ebi.ac.uk/public-datasets/bioimage.io/available_ids.json

Make sure to select an ID from for the appropriate description type ('model', 'dataset' or 'notebook')

I just added confirmation to our Terms of Service in the issue template and do not have time right now to finish this update, so I'm afraid this upload option is not yet available. I try finish this asap!!

As a goodie I also add in that the upload does not need an id, in which case it will be chosen randomly. 

More details will follow soon. Thank you for your tremendous patience!

**Comment by mattaq31** [comment]
Ok that's no problem - please do let me know when the update is complete.  I'll probably place the upload onto a temporary download link for the GitHub issue (if a direct upload is available that would also be very useful).

**Comment by FynnBe** [comment]
I think [upload via issue](https://github.com/bioimage-io/collection/issues/new?template=bioimageiobot-please-upload.yaml) is ready (and if not I'll upload any resource posted in [such an issue](https://github.com/bioimage-io/collection/issues/new?template=bioimageiobot-please-upload.yaml) manually ;-) )
See https://github.com/bioimage-io/collection/issues/135 for an example.

**Comment by mattaq31** [comment]
Thanks @FynnBe  - I've added two models: https://github.com/bioimage-io/collection/issues/136 and https://github.com/bioimage-io/collection/issues/137 - seems like one has errored out?  Not sure what the error message means though..

**Comment by FynnBe** [comment]
> seems like one has errored out? Not sure what the error message means though..

answered in the respective new issues... 

bioimage.io login remains offline. I'm getting
```
Uncaught (in promise) Timeout Error: Failed to get remote service: */manager-statuesque-gerbil-08887958:default
```

**Comment by oeway** [comment]
It looks the issue is coming from somewhere else in the cluster, I am disable the redis server (which we used internally for communication within the cluster) see if it makes the service more stable. I will keep an eye on this. Sorry about this.

**Comment by FynnBe** [comment]
this seems to have fixed it. Please reopen if the issue reoccurs

**Comment by FynnBe** [comment]
hmm. even though it works (I seem to be logged in) I did get this pop up now..

![Image](https://github.com/user-attachments/assets/9d1e27a0-45d2-4af9-b5cb-33bab0ed6539)
